spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bulletfly?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: BulletFly1022,,.
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request